name: Build and Test 🚀✅

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
    paths:
    - 'src/sdk/PnP.Core/**'
    - 'src/sdk/PnP.Core.Auth/**'
    - 'src/sdk/PnP.Core.Admin/**'
    - 'src/sdk/PnP.Core.Transformation/**'
    - 'src/sdk/PnP.Core.Transformation.SharePoint/**'
    - 'src/sdk/PnP.Core.Test/**'
    - 'src/sdk/PnP.Core.Auth.Test/**'
    - 'src/sdk/PnP.Core.Admin.Test/**'
    - 'src/sdk/PnP.Core.Transformation.Test/**'
    - 'src/sdk/PnP.Core.Transformation.SharePoint.Test/**'
  pull_request:
    branches: [ dev ]
    paths:
    - 'src/sdk/PnP.Core/**'
    - 'src/sdk/PnP.Core.Auth/**'
    - 'src/sdk/PnP.Core.Admin/**'
    - 'src/sdk/PnP.Core.Transformation/**'
    - 'src/sdk/PnP.Core.Transformation.SharePoint/**'
    - 'src/sdk/PnP.Core.Test/**'
    - 'src/sdk/PnP.Core.Auth.Test/**'
    - 'src/sdk/PnP.Core.Admin.Test/**'
    - 'src/sdk/PnP.Core.Transformation.Test/**'
    - 'src/sdk/PnP.Core.Transformation.SharePoint.Test/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Wait for actions to finish
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}              
    - name: Checkout dev branch
      uses: actions/checkout@v2
      with: 
        ref: dev
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        include-prerelease: false
    - name: Install dependencies
      run: dotnet restore
      working-directory: src/sdk
    - name: Build ⚙
      run:  dotnet build --configuration debug --no-restore --verbosity normal 
      working-directory: src/sdk   
    - name: Test 🧪
      env:
        pnpcoresdktestsite: ${{ secrets.PNPCORESDKTESTSITE }}
        pnpcoresdktestuser: ${{ secrets.PNPCORESDKTESTUSER }}
        pnpcoresdktestuserpassword: ${{ secrets.PNPCORESDKTESTUSERPASSWORD }}
      run: |
        dotnet test ./PnP.Core.Test/PnP.Core.Test.csproj --no-restore --verbosity normal --collect:"XPlat Code Coverage"
        dotnet test ./PnP.Core.Auth.Test/PnP.Core.Auth.Test.csproj --no-restore --verbosity normal --collect:"XPlat Code Coverage"
        dotnet test ./PnP.Core.Admin.Test/PnP.Core.Admin.Test.csproj --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: src/sdk    
    - name: Upload coverage to Codecov 📝
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: src/sdk/**/coverage.cobertura.xml        
