name: Nightly nuget release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
    
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Wait for actions to finish
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with: 
        ref: dev
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'    
        include-prerelease: false
    - name: Create and publish nuget 
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      shell: pwsh
      run: |
        ./build/build.ps1
    # Add, commit and push changes
    - name: Add & Commit & Push
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Nightly PnP Framework release'
        push: true
        branch: dev
        token: ${{ secrets.GITHUB_TOKEN }}    
